### ISSUE TITLE
Downloading mods is broken

### ISSUE THREAD

**Issue by Ashymad** [Misza13/carrot#2]
Since the curseforge project page redesign and merger carrot doesn't download the mod file, it saves the "Description" page html as the mod file instead.

**Comment by Misza13** [comment]
Bug confirmed, thanks for the heads up.

In fact, the problem is not with Carrot itself but my web crawler that's been indexing the old CurseForge site. It needs to be adjusted to the new pages; I'm on it.

**Comment by Misza13** [comment]
Full crawl has now completed with new rules. Carrot should work fine now (no update needed).

@Ashymad Nice to see btw that someone else is actually using this. :)

**Comment by Ashymad** [comment]
Thank you for fixing this! And thank you for writing this. It is so much more convenient than managing the mods manually :)
